Iter5
greyfox12/Metrics pull request #5
Opened 2023-07-14 17:45 UTC by greyfox12

2023-07-15 16:00 UTC, kilchik requested changes

2023-07-15 16:00 UTC, kilchik commented on cmd/agent/main.go
> +	var cfg Config
Нужно поработать над структурой проекта уже сейчас. Даже большие программы можно написать в одном файле, однако пока мы учимся, лучше сразу привыкать писать в соответствии с best practices - они придуманы не случайно, а путем натыкания на большое число граблей.
В cmd должны остаться лишь main.go, остальное нужно разнести по пакетам. Чаще всего вспомогательные пакеты располагают в /pkg (в твоем случае те сущности, которые универсальны и для агента, и для сервера) и /internal (например, пакет /internal/server/storage или /internal/storage для взаимодействия с хранилищем метрик).
Для вдохновения стоит ознакомиться с проектом https://github.com/golang-standards/project-layout - в нем описаны лучшие практики структурирования реальных проектов

2023-07-15 16:00 UTC, kilchik commented on cmd/agent/main.go
> +	cfg.address, _ = os.LookupEnv("ADDRESS")
Не следует игнорировать ошибки, обработка ошибок обязательна в любом языке, Go же навязывает явную обработку ошибки в том месте, где она произошла. Все ошибки без исключения нужно обработать

2023-07-15 16:00 UTC, kilchik commented on cmd/agent/post.go
> +	//	fmt.Printf("URL: %v\n", c.url)
Лишние комментарии лучше убрать

2023-07-15 16:00 UTC, kilchik commented on cmd/agent/post.go
> +			fmt.Printf("Error: %v\n", err)
Зачем возвращается int? Если нужно вызывающей функции вернуть ошибку, то следует обрамить err префиксом и вернуть в вызывающую функцию. Префикс нужен для того, чтобы можно было однозначно определить, в каком месте произошла ошибка, и кто пытался ее обработать. 
Для обрамления можно воспользоваться либо пакетом `github.com/pkg/errors` и обернуть `errors.Wrap(err, "post request")`, либо стандартным `fmt.Errorf("post request: %w", err)`

2023-07-15 16:00 UTC, kilchik commented on cmd/server/handler.go
> +		aSt := strings.Split(req.URL.Path, "/")
Для меньшей вложенности кода лучше использовать быстрый выход, например так:
```
if req.Method != http.MethodPost {
  res.WriteHeader(http.StatusMethodNotAllowed)
  return
}
```

2023-07-15 16:00 UTC, kilchik commented on cmd/server/main.go
> +var MemMetric tMetric
Старайся не создавать глобальные объекты никогда, единственным возможным исключением на практике может стать logger. Глобальные объекты чреваты
* огромными затруднениями при написании тестов
* сложноотловимыми багами, связанными с рейсами (к MemMetric могут обратиться из любой горутины на чтение + запись)
* сложноотловимыми багами в целом, потому что к объекту есть доступ из любого куска кода, очень сложно локализовать изменение, приведшее к багу

2023-07-15 16:00 UTC, kilchik commented on cmd/server/main.go
> +	gauge   map[string]float64
Мапы в Go не являются потокобезопасным примитивом. В данном случае к gauge и counter может обращаться код из обработчиков (каждый из них бежит в своей горутине) на чтение+запись одновременно.
Для решения этой проблемы стоит воспользоваться примитивом синхронизации, например, sync.Mutex
https://go.dev/blog/maps

2023-07-19 20:53 UTC, greyfox12 commented on cmd/agent/main.go
> +	var cfg Config
Разделил агент и сервер на функциональные части по разным пакетам, разложил их по структуре

2023-07-19 20:54 UTC, greyfox12 commented on cmd/agent/main.go
> +	cfg.address, _ = os.LookupEnv("ADDRESS")
Добавил обработку ошибок

2023-07-19 20:56 UTC, greyfox12 commented on cmd/agent/post.go
> +	//	fmt.Printf("URL: %v\n", c.url)
Почистил код от отладки

2023-07-19 20:58 UTC, greyfox12 commented on cmd/agent/post.go
> +			fmt.Printf("Error: %v\n", err)
Исправил. Наследство от С

2023-07-19 20:58 UTC, greyfox12 commented on cmd/server/handler.go
> +		aSt := strings.Split(req.URL.Path, "/")
Исправил

2023-07-19 21:00 UTC, greyfox12 commented on cmd/server/main.go
> +var MemMetric tMetric
Изменил взаимодействие с переменными. Выделил отдельно пакет работы с storage

2023-07-19 21:01 UTC, greyfox12 commented on cmd/server/main.go
> +	gauge   map[string]float64
Перенес работу с мапами в отдельный пакет storage. Воспользоваться примитивом синхронизации sync.Mutex в пакете

2023-07-20 16:19 UTC, kilchik approved these changes

2023-07-20 19:11 UTC, merged