Iter9
greyfox12/Metrics pull request #9
Opened 2023-07-29 15:17 UTC by greyfox12

2023-08-01 16:51 UTC, kilchik requested changes
При StoreInterval=0 нужно сохранять данные синхронно по аналогии с сохранением в памяти

2023-08-01 16:51 UTC, kilchik commented on cmd/server/main.go
> +				time.Sleep(time.Duration(vServerParam.StoreInterval) * time.Second)
В Go в подобных случаях лучше использовать time.Ticker, в отличие от Sleep от учитывает время выполнения функции SaveMetric и подстраивает интервал для следующего вызова

2023-08-01 16:51 UTC, kilchik commented on internal/agent/compress/compress.go
> +		return nil, fmt.Errorf("failed init compress writer: %v", err)
Тут и в других вызовах fmt.Errorf стоит использовать %w - так в обработчике ошибок удастся развернуть полученную ошибку до исходной функциями errors.Is и errors.As

2023-08-01 16:51 UTC, kilchik commented on internal/agent/post/post.go
> +		defer response.Body.Close()
Закрывать Body нужно даже если ReadAll вернула ошибку - иначе есть вероятность утечки файловых дискрипторов

2023-08-01 16:51 UTC, kilchik commented on internal/agent/post/post.go
> +			//			Timeout: time.Second * 10,
http.Client по-умолчанию имеет бесконечный Timeout, что критично для агента, отсылающего метрики. Представь, что один из вызовов подвис - для сервера важнее получить актуальные данные, чем полные но с задержкой

2023-08-01 16:51 UTC, kilchik commented on internal/agent/post/post.go
> +	/*	// проверяю value
Лишние комментарии стоит убрать

2023-08-03 04:14 UTC, greyfox12 commented on internal/agent/post/post.go
> +	/*	// проверяю value
Убрал

2023-08-03 04:15 UTC, greyfox12 commented on cmd/server/main.go
> +				time.Sleep(time.Duration(vServerParam.StoreInterval) * time.Second)
Изменил

2023-08-03 04:15 UTC, greyfox12 commented on internal/agent/compress/compress.go
> +		return nil, fmt.Errorf("failed init compress writer: %v", err)
Изменил

2023-08-03 04:15 UTC, greyfox12 commented on internal/agent/post/post.go
> +		defer response.Body.Close()
Исправил

2023-08-03 04:15 UTC, greyfox12 commented on internal/agent/post/post.go
> +			//			Timeout: time.Second * 10,
Исправил

2023-08-05 18:59 UTC, kilchik approved these changes

2023-08-06 20:15 UTC, merged